---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inform
  template:
    metadata:
      labels:
        app: inform
    spec:
      serviceAccountName: inform
      securityContext: {}
      containers:
        - name: inform
          securityContext: {}
          image: "jpetersenames/inform:v0.0.2"
          imagePullPolicy: IfNotPresent
          command:
            - "inform"
            - "--in-cluster"
          livenessProbe:
            exec:
              command:
                - inform
                - --help
            initialDelaySeconds: 1
            timeoutSeconds: 10
            periodSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - inform
                - --help
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          resources: {}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inform-read-only
subjects:
  - kind: ServiceAccount
    name: inform
    namespace: default
roleRef:
  kind: ClusterRole
  name: inform-read-only
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inform-read-only
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inform
  namespace: default
