apiVersion: apps/v1
kind: Deployment
metadata:
  name: inform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inform
  template:
    metadata:
      labels:
        app: inform
    spec:
      serviceAccountName: inform
      containers:
        - name: inform
          image: jpetersenames/inform:v0.0.1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inform-read-only
subjects:
  - kind: ServiceAccount
    name: inform
    namespace: default
roleRef:
  kind: ClusterRole
  name: inform-read-only
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inform-read-only
rules:
- apiGroups: [""]
  resources: ["pods","namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inform
  namespace: default
