on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Melange Build
        uses: chainguard-dev/actions/melange-build@main
        with:
          config: build/inform.melange.yaml
          sign-with-temporary-key: true

      - name: APKO Build
        uses: chainguard-images/actions/apko-build@main
        with:
          config: build/inform.apko.yaml
          tag: ghcr.io/${{ github.actor }}/inform:${{ github.sha }}
          keyring-append: melange.rsa.pub

      - name: Test image load
        shell: bash
        run: |
          set -x
          docker load -i output.tar

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        shell: bash
        run: |
          set -x
          export PULLSTRING="$(docker load -i output.tar | grep 'Loaded image:' | cut -d' ' -f3)"
          echo "${PULLSTRING}"
          docker push "${PULLSTRING}"
