on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          find . -not -path '*/.*'

      - name: Melange Build
        id: melange
        uses: chainguard-dev/actions/melange-build@main
        with:
          config: melange.yaml
          sign-with-temporary-key: true

      - run: |
          find . -not -path '*/.*'

      - name: APKO Build
        id: apko
        uses: chainguard-images/actions/apko-build@main
        with:
          config: image.yaml
          tag: jpetersenames/inform:${{ github.sha }}
          keyring-append: melange.rsa.pub

      - run: |
          find . -not -path '*/.*'

      - name: Testing
        id: test
        shell: bash
        run: |
          set -x
          docker load < output.tar
