on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run something
        run: |
          echo "What is the current directory"
          pwd

          echo "Listing directory"
          ls

          echo "hello"
      - name: Melange Build
        id: melange
        uses: chainguard-dev/actions/melange-build@main
        with:
          config: melange.yaml
          sign-with-temporary-key: true
      - name: APKO Build
        id: apko
        uses: chainguard-images/actions/apko-build@main
        with:
          config: image.yaml
          tag: jpetersenames/inform:${{ github.sha }}
          keyring-append: melange.rsa.pub
      - name: Testing
        id: test
        shell: bash
        run: |
          set -x
          docker load < output.tar
