on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run something
        run: |
          echo "What is the current directory"
          pwd

          echo "Listing directory"
          ls

          echo "hello"
